# Generated by Django 4.2.4 on 2023-08-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCPLapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='finalplu',
            table=' Final_PLU',
        ),
    ]
